### ISSUE TITLE
Dockerfile build failed due to conda update

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids-ml#415]
failed to build ci/dockerfile due to missed specific openssl version. 

related to https://github.com/mamba-org/mamba/issues/2788

```
[2023-08-27T01:58:35.148Z] 

[2023-08-27T01:58:35.148Z] ───────────────────────────────────────────────────────────────────────────────────────────────────

[2023-08-27T01:58:35.148Z] 

[2023-08-27T01:58:35.148Z] 

[2023-08-27T01:58:35.148Z] error    libmamba Failed to download package from https://conda.anaconda.org/conda-forge/openssl-3.1.2-hd590300_0.conda (status 404)

[2023-08-27T01:58:35.148Z] 

[2023-08-27T01:58:35.148Z] Looking for: ['cuml=23.08', 'python=3.9', 'cuda-version=11.5']

[2023-08-27T01:58:35.148Z] 

[2023-08-27T01:58:35.148Z] Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/openssl-3.1.2-hd590300_0.conda] 956 bytes

[2023-08-27T01:58:35.148Z] 

[2023-08-27T01:58:35.148Z] # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

[2023-08-27T01:58:35.148Z] 

[2023-08-27T01:58:35.148Z]     Traceback (most recent call last):

[2023-08-27T01:58:35.148Z]       File "/root/miniconda3/lib/python3.8/site-packages/conda/exception_handler.py", line 16, in __call__

[2023-08-27T01:58:35.148Z]         return func(*args, **kwargs)

[2023-08-27T01:58:35.148Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 926, in exception_converter

[2023-08-27T01:58:35.148Z]         raise e

[2023-08-27T01:58:35.148Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 919, in exception_converter

[2023-08-27T01:58:35.148Z]         exit_code = _wrapped_main(*args, **kwargs)

[2023-08-27T01:58:35.148Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 877, in _wrapped_main

[2023-08-27T01:58:35.148Z]         result = do_call(parsed_args, p)

[2023-08-27T01:58:35.148Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 748, in do_call

[2023-08-27T01:58:35.148Z]         exit_code = install(args, parser, "install")

[2023-08-27T01:58:35.148Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 557, in install

[2023-08-27T01:58:35.148Z]         transaction.fetch_extract_packages()

[2023-08-27T01:58:35.148Z]     RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/openssl-3.1.2-hd590300_0.conda] 956 bytes

[2023-08-27T01:58:35.148Z] 

[2023-08-27T01:58:35.148Z] `$ /root/miniconda3/bin/mamba install -y -c rapidsai -c conda-forge -c nvidia cuml=23.08 python=3.9 cuda-version=11.5`
```

**Comment by pxLi** [comment]
seems it changed every run
```

[2023-08-26T01:58:28.165Z] 

[2023-08-26T01:58:28.165Z] error    libmamba Failed to download package from https://conda.anaconda.org/conda-forge/dlpack-0.5-h9c3ff4c_0.tar.bz2 (status 404)

[2023-08-26T01:58:28.165Z] Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/dlpack-0.5-h9c3ff4c_0.tar.bz2] 955 bytes

[2023-08-26T01:58:28.165Z] 

[2023-08-26T01:58:28.165Z] # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

[2023-08-26T01:58:28.165Z] 

[2023-08-26T01:58:28.165Z]     Traceback (most recent call last):

[2023-08-26T01:58:28.165Z]       File "/root/miniconda3/lib/python3.8/site-packages/conda/exception_handler.py", line 16, in __call__

[2023-08-26T01:58:28.165Z]         return func(*args, **kwargs)

[2023-08-26T01:58:28.165Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 926, in exception_converter

[2023-08-26T01:58:28.165Z]         raise e

[2023-08-26T01:58:28.165Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 919, in exception_converter

[2023-08-26T01:58:28.165Z]         exit_code = _wrapped_main(*args, **kwargs)

[2023-08-26T01:58:28.165Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 877, in _wrapped_main

[2023-08-26T01:58:28.165Z]         result = do_call(parsed_args, p)

[2023-08-26T01:58:28.165Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 748, in do_call

[2023-08-26T01:58:28.165Z]         exit_code = install(args, parser, "install")

[2023-08-26T01:58:28.165Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 557, in install

[2023-08-26T01:58:28.165Z]         transaction.fetch_extract_packages()

[2023-08-26T01:58:28.165Z]     RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/dlpack-0.5-h9c3ff4c_0.tar.bz2] 955 bytes

[2023-08-26T01:58:28.165Z] 

[2023-08-26T01:58:28.165Z] `$ /root/miniconda3/bin/mamba install -y -c rapidsai -c conda-forge -c nvidia cuml=23.08 python=3.9 cuda-version=11.5`
```

**Comment by pxLi** [comment]
@eordentlich as some scripts in repo already relying on the mamba to speed up the conda installation,
we may need to to decide if we would like to wait for the fix of https://github.com/mamba-org/mamba/issues/2788
or just switch all usages to `conda` directly

**Comment by eordentlich** [comment]
Thank you @pxLi for resolving this.

**Comment by pxLi** [comment]
reopened as https://github.com/NVIDIA/spark-rapids-ml/pull/416 which caused intermittent error https://github.com/mamba-org/mamba/issues/1728

we may consider the new conda solver to use libmamba directly
```
conda update -n base conda
conda install -n base conda-libmamba-solver
conda config --set solver libmamba
```

I will verify the solution in coming days
