### ISSUE TITLE
Crash when calling fit passing a DataFrame

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids-ml#57]
I am in the process of bechmarking different runtimes for using this library but when I use a file that is 1.6 gb, the spark job crashes with the following exception 

```
22/01/31 21:02:31 WARN package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
22/01/31 21:02:32 WARN DAGScheduler: Broadcasting large task binary with size 1105.3 KiB
22/01/31 21:02:50 WARN DAGScheduler: Broadcasting large task binary with size 1970.1 KiB
22/01/31 21:04:00 WARN TaskSetManager: Lost task 12.0 in stage 5.0 (TID 41) (192.168.1.250 executor 0): java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:430)
	at scala.collection.immutable.Nil$.head(List.scala:427)
	at org.apache.spark.ml.linalg.distributed.RapidsRowMatrix.$anonfun$computeCovariance$1(RapidsRowMatrix.scala:134)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The script being used to write the parquet file is 

```
import org.apache.spark.ml.linalg._
import org.apache.spark.sql.functions._
val rows = 100000
val dim = 2048
val r = new scala.util.Random(0)
var prepareDf = spark.createDataFrame(
(0 until rows).map(_ => Tuple1(Array.fill(dim)(r.nextDouble)))).
withColumnRenamed("_1", "array_feature").
select((0 until dim).map(i => col("array_feature").getItem(i)): _*)
prepareDf.write.mode("overwrite").parquet("PCA_raw_parquet")
```

The script used to reduce the DF and apply the fit method is 

```

val df = spark.read.parquet("PCA_raw_parquet")
val dim = 2048
val avgValue = df.select(
(0 until dim).map("array_feature[" + _ + "]").map(col).map(avg): _*).first()
val inputCols = (0 until dim).map(i =>
(col("array_feature[" + i + "]") - avgValue.getDouble(i)).alias("feature_"+i))
val meanCenterDf = df.select(inputCols:_*)

val dataDf = meanCenterDf.withColumn("feature",array(meanCenterDf.columns.map(col):_*)).select("feature").cache()
val pcaGpu = new com.nvidia.spark.ml.feature.PCA().setInputCol("feature").setOutputCol("pca_features").setK(3)
val pcaModelGpu = spark.time(pcaGpu.fit(dataDf))
```

**Comment by wjxiz1992** [comment]
It's saying that one input partition(RDD[Table]) contains 0 Table. I'm taking a more close look at it. Will update ASAP.
