### ISSUE TITLE
[Bug] Nightly test failed: RuntimeError: Cannot import pyspark `unwrap_udt` function

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids-ml#578]
Detailed log as below:

spark-rapids-ml_nightly/312;  spark-rapids-ml_nightly/313

```
 WARNING: Spark Param 'family' is not used by cuML.
 stopping spark session
 Traceback (most recent call last):
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/src/spark_rapids_ml/utils.py", line 478, in _get_unwrap_udt_fn
     from pyspark.databricks.sql.functions import unwrap_udt as databricks_unwrap_udt
 ModuleNotFoundError: No module named 'pyspark.databricks'
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/./benchmark/benchmark_runner.py", line 83, in <module>
     BenchmarkRunner().run()
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/./benchmark/benchmark_runner.py", line 67, in run
     self._runner.run()
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/benchmark/benchmark/base.py", line 241, in run
     benchmark_results, benchmark_time = with_benchmark(
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/benchmark/benchmark/utils.py", line 44, in with_benchmark
     result = action()
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/benchmark/benchmark/base.py", line 243, in <lambda>
     lambda: self.run_once(
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/benchmark/benchmark/bench_logistic_regression.py", line 81, in run_once
     model, fit_time = with_benchmark(benchmark_string, lambda: lr.fit(train_df))
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/benchmark/benchmark/utils.py", line 44, in with_benchmark
     result = action()
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/benchmark/benchmark/bench_logistic_regression.py", line 81, in <lambda>
     model, fit_time = with_benchmark(benchmark_string, lambda: lr.fit(train_df))
   File "/root/miniconda3/lib/python3.9/site-packages/pyspark/ml/base.py", line 205, in fit
     return self._fit(dataset)
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/src/spark_rapids_ml/core.py", line 1036, in _fit
     return self._fit_internal(dataset, None)[0]
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/src/spark_rapids_ml/core.py", line 1000, in _fit_internal
     pipelined_rdd = self._call_cuml_fit_func(
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/src/spark_rapids_ml/core.py", line 638, in _call_cuml_fit_func
     select_cols, multi_col_names, dimension, _ = self._pre_process_data(dataset)
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/src/spark_rapids_ml/classification.py", line 1131, in _pre_process_data
     ) = super()._pre_process_data(dataset)
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/src/spark_rapids_ml/core.py", line 1088, in _pre_process_data
     ) = super()._pre_process_data(dataset)
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/src/spark_rapids_ml/core.py", line 501, in _pre_process_data
     select_cols += _get_unwrapped_vec_cols(col(input_col))
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/src/spark_rapids_ml/core.py", line 161, in _get_unwrapped_vec_cols
     unwrap_udt = _get_unwrap_udt_fn()
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-313/python/src/spark_rapids_ml/utils.py", line 482, in _get_unwrap_udt_fn
     raise RuntimeError(
 RuntimeError: Cannot import pyspark `unwrap_udt` function. Please install pyspark>=3.4 or run on Databricks Runtime.
script returned exit code 1
```

**Comment by NvTimLiu** [comment]
Looks like this issue was reported among the recent commits: from `bd7676a`  to    `a969849`

![image](https://github.com/NVIDIA/spark-rapids-ml/assets/50287591/34f0c789-ff09-480b-8eb8-3b5401483160)

**Comment by lijinf2** [comment]
This has been fixed. Please check. @NvTimLiu
