### ISSUE TITLE
[Bug] Nightly integration test failed: NUM_COLUMNS_MISMATCH] UNION can only be performed on inputs with the same number of columns, but the first input has 3 columns and the second input has 4 columns.;

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids-ml#604]
Nightly integration test failed: NUM_COLUMNS_MISMATCH] UNION can only be performed on inputs with the same number of columns, but the first input has 3 columns and the second input has 4 columns.;

Not sure if it related to : [ARG CUML_VER=24.02](https://github.com/NVIDIA/spark-rapids-ml/blob/branch-24.04/ci/Dockerfile#L40) on branch-24.04

```
c18#82751, c19#82752, c20#82753, c21#82754, c22#82755, ... 27 more fields]
15:32:05           +- LogicalRDD [c0#82733, c1#82734, c2#82735, c3#82736, c4#82737, c5#82738, c6#82739, c7#82740, c8#82741, c9#82742, c10#82743, c11#82744, c12#82745, c13#82746, c14#82747, c15#82748, c16#82749, c17#82750, c18#82751, c19#82752, c20#82753, c21#82754, c22#82755, c23#82756, ... 26 more fields], false
15:32:05  
15:32:05  	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:52)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$36(CheckAnalysis.scala:585)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$36$adapted(CheckAnalysis.scala:576)
15:32:05  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
15:32:05  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
15:32:05  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$1(CheckAnalysis.scala:576)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$1$adapted(CheckAnalysis.scala:163)
15:32:05  	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:295)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:163)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:160)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:188)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:156)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:146)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:188)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:211)
15:32:05  	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
15:32:05  	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:208)
15:32:05  	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:76)
15:32:05  	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
15:32:05  	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:202)
15:32:05  	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:526)
15:32:05  	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:202)
15:32:05  	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
15:32:05  	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:201)
15:32:05  	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:76)
15:32:05  	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:74)
15:32:05  	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:66)
15:32:05  	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:89)
15:32:05  	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
15:32:05  	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:87)
15:32:05  	at org.apache.spark.sql.Dataset.withSetOperator(Dataset.scala:4247)
15:32:05  	at org.apache.spark.sql.Dataset.union(Dataset.scala:2355)
15:32:05  	at sun.reflect.GeneratedMethodAccessor395.invoke(Unknown Source)
15:32:05  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:32:05  	at java.lang.reflect.Method.invoke(Method.java:498)
15:32:05  	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
15:32:05  	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
15:32:05  	at py4j.Gateway.invoke(Gateway.java:282)
15:32:05  	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
15:32:05  	at py4j.commands.CallCommand.execute(CallCommand.java:79)
15:32:05  	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
15:32:05  	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
15:32:05  	at java.lang.Thread.run(Thread.java:750)
15:32:05  ========= 12 failed, 665 passed, 8452 warnings in 10694.17s (2:58:14) ==========
```

**Comment by eordentlich** [comment]
Fixed.
